test_ratio: 0.3
automl_max_evals: 10
# project_id: "blent-sandbox-8972132652"
# bucket_path: "gs://blent-purchase-predict-bucket"
mlflow_experiment_id: 1
log_to_mlflow: True
mlflow_model_registry: "purchase_predict"
