name: Code quality checks

on:
  push:
    branches: [ dev, master ]
  # pull_request:
  #   branches: [ dev, master ]
jobs: 
  build-venv:
    runs-on: ubuntu-latest

    steps:
      
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Build environment
        run: |
          python -m venv venv
          echo "VENV_DIR=$(pwd)/venv" >> $GITHUB_ENV
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          echo "Environment was created successfully!"

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run isort
        run: |
          isort --diff --color src/purchase_predict/* tests/* docs/source/*.py
        continue-on-error: false # stop commit if there is an error
      - name: Run black
        run: black --diff --color src/purchase_predict/* tests/* docs/source/*.py
        continue-on-error: false 
      - name: ruff check
        run: ruff check src/purchase_predict/* tests/* docs/source/*.py
        continue-on-error: true
      - name: Pylint batch
        uses: Silleellie/pylint-github-action@v2
        with: 
          lint-path: src/purchase_predict/* tests/*.py
          python-version: 3.12
          requirements-path: requirements.txt 
          readme-path: README.md
          badge-text: PyLint Score
          color-bad-score: red
          color-ok-score: orange
          color-good-score: yellow
          color-perfect-score: brightgreen




