name: Lint with pylint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint  # Install pylint
          pip install -r requirements.txt  # Install your project dependencies

      - name: Run pylint
        run: |
          pylint src/**/*.py > pylint_report.txt || true
        continue-on-error: true
      - name: Display report
        run: |
          cat pylint_report.txt

      - name: Display pylint score
        run: |
          score=$(tail -n 1 pylint_report.txt | grep -oP '(?<=rated at )\d+\.\d+')
          echo "Pylint score: $score"
